name: CI

on: 
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 9999
    
    steps:
    - name: CLU
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText $Env:WINDOWS_USER_PASSWORD -Force)
      env:
        WINDOWS_USER_PASSWORD: ${{ secrets.WINDOWS_USER_PASSWORD }}
    - name: Download
      run: |
       Invoke-WebRequest https://download.anydesk.com/AnyDesk.exe -OutFile AnyDesk.exe
       Invoke-WebRequest https://raw.githubusercontent.com/emingili/outatiam/master/aidi.bat -OutFile aidi.bat
       Invoke-WebRequest https://raw.githubusercontent.com/emingili/outatiam/master/myps.bat -OutFile myps.bat
    - name: Install
      run: .\anydesk.exe --install "C:\Program Files (x86)\AnyDesk" --start-with-win
    - name: Sleep
      run: sleep 5
    - name: Show ID
      run: .\aidi.bat
    - name: Setup PSWORD
      run: .\myps.bat
    - name: Loop
      run: sleep 99999